### ISSUE TITLE
Rendering Failes for lineargauge-overview

### ISSUE THREAD

**Issue by alhalama** [Infragistics/livewire#130]
View: [lineargauge-overview.zip](https://github.com/Infragistics/livewire/files/1439403/lineargauge-overview.zip)

Result:
Uncaught TypeError: Cannot read property 'replace' of undefined
    at Object.<anonymous> (C:\git\ig\livewire\app\modules\results\asciidoc.js:36:33)
    at initialize.exports.each (C:\git\ig\livewire\app\node_modules\cheerio\lib\api\traversing.js:293:24)
    at Worker.message (C:\git\ig\livewire\app\modules\results\asciidoc.js:33:14)

Expected Result: Rendering should complete

**Comment by alhalama** [comment]
@mharrington622 this is related to the logic for showing hyperlinks as tooltips.

**Comment by alhalama** [comment]
It appears to be caused by the following content in the file:
* [[_ReservedAreaLink]]*Reserved area* pick:[sl,wpf="(1)"] 
*  [[_GraphAreaLink]]*Graph area* pick:[sl,wpf="(2)"]
